config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: {
  registrations: "users/registrations"
  }

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]

  get "search" => "search#search"

  resources :users do
    member do
      get :followings, :followers
    end
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す


  get 'chats/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(5).pluck(:book_id))
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(5).pluck(:book_id))
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end
  
  
  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.following_user
  end
    
  def followers
    @user = User.find(params[:id])
    @followers = @user.follower_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <div class="col-md-3">
   <%= render 'books/list', user: @user, book: @book %>
  </div>

  <div class="col-md-8 offset-md-1">
    　<h2>Books</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
       <% @books.each do |book| %>
       <tr>
         <td>
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg" %>
          <% end %>
         </td>
         <td><%= link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
         <td class="favorite-buttons_<%= book.id %>">
          <%= render 'favorites/favorites', book: book %>
         </td>
         <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
       </tr>
       <% end %>
     </tbody>
   </table>
  </div>

 </div>
</div>

#普通のBooks/index

app/views/books/_list.html.erb
     <% if book.errors.any? %>
     <%= book.errors.count %>errors prohibited this obj from being saved:
     <% book.errors.full_messages.each do |message| %>
     <%= message %>
     <% end %>
     <% end %>
    <h2>User info</h2>
       <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
   <table class="table">
  　<tbody>
     <tr>
	     <th>name</th>
	     <th><%= user.name %></th>
     </tr>
     <tr>
	     <th>introduction</th>
	     <th><%= user.introduction %></th>
	    </tr>
	    <tr>
	     <th>follows</th>
	     <th><%= link_to "#{user.follower.count}", followings_user_path(user.id)  %></th>
	    </tr>
	    <tr>
	     <th>followers</th>
	     <th><%= link_to "#{user.followed.count}", followers_user_path(user.id)  %></th>
     </tr>
    </tbody>
   </table>
      <% unless user == current_user %>
           <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :DELETE,class:"btn btn-success" %>
           <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST,class:"btn btn-success" %>
           <% end %>
          <%= link_to 'Chatを始める', chat_path(user.id) %>
      <% else %>
           <%= link_to edit_user_path(user) do %>
            <div class="row">
             <i class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog" ></i></i>
            </div>
           <% end %>
      <% end %>
       <h2 class="mt-3">New book</h2>
       <%= form_with model: book, local:true do |f| %>
        <div class="form-group">
         <label for="book_title">Title</label>
         <%= f.text_field :title,class:"form-control book_title" %>
        </div>
        <div class="form-group">
         <label for="book_opinion">Opinion</label>
         <%= f.text_area :body,class:"form-control book_body" %>
        </div>
        <div class="form-group">
         <%= f.submit 'Create Book',class:"btn btn-success" %>
        <% end %>
        </div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		  <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
      <% @book.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    <% end %>
     <%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
     <label for="book_title">Title</label>
      <%= f.text_field :title, class:"form-control book_title" %>
    </div>
    <div class="form-group">
     <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"form-control book_body" %>
    </div>
    <div class="form-group">
     <%= f.submit 'Update Book',class:"btn btn-success" %>
     <% end %>
    </div>

  		<%= link_to "Show", book_path(@book) %> |
  		<%= link_to "Back", books_path, class:"back" %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

  <div class="col-md-3">
   <%= render 'books/list', user: @user, book: @book %>
  </div>

  <div class="col-md-8 offset-md-1">
    　<h2>Books</h2>
    　<h2>いいね数ランキング</h2>
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
  　  　<% lastFavorite = 0 %>
       <% j = 1 %>
       <% @all_ranks.each.with_index(1) do |book, i| %>
          <% if i == 1 %>
           <% lastFavorite = book.favorites.count %>
          <% end %>
       <tr>
         <td>
          <% if book.favorites.count != lastFavorite %>
          <% j = i %>

          第<%= j %>位
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg" %>
          <% end %>
         </td>
         <td><%= link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
         <td class="favorite-buttons_<%= book.id %>">
          <%= render 'favorites/favorites', book: book %>
         </td>
         <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
       </tr>
       <tr>
         <% lastFavorite = book.favorites.count %>
         <% else %>
         <% lastFavorite = book.favorites.count %>

         第<%= j %>位
         <%= link_to user_path(book.user.id) do %>
         <%= attachment_image_tag book.user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg" %>
         <% end %>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td class="favorite-buttons_<%= book.id %>">
          <%= render 'favorites/favorites', book: book %>
        </td>
        <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
         <% end %>
       </tr>
       <% end %>
     </tbody>
   </table>
  </div>

 </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

   <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book_new %>
   </div>


   <div class="col-md-8 offset-md-1">
     <h2>Book detail</h2>
    <table class="table">
     <tbody>
      <tr>
       <td>
        <%= link_to user_path(@user) do %>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 90, 100, fallback: "no_image.jpg" %><br>
        <% end %>
        <%= link_to @user.name, user_path(@user) %>
       </td>
       <td><%= link_to @book.title, book_path(@book) %></td>
       <td><%= @book.body %></td>
       <td class="favorite-buttons_<%= @book.id %>">
          <%= render 'favorites/favorites', book: @book %>
       </td>
       <td class="count"><%= render 'book_comments/book_count', book: @book %></td>
       <% if @book.user == current_user %>
       <td><%= link_to "Edit", edit_book_path(@book),class:"btn btn-sm btn-success" %></td>
       <td><%= link_to "Destroy",book_path(@book), method: :delete,class:"btn btn-sm btn-danger" %></td>
        <% end %>
      </tr>
     </tbody>
    </table>


          <div class="destroy-comment-button">
            <%= render 'book_comments/book_comments', book: @book %>
          </div>

             <% if @book.errors.any? %>
             <%= @book.errors.count %>error prohibited this obj from being saved:
             <% @book.errors.full_messages.each do |message| %>
             <%= message %>
             <% end %>
             <% end %>

          <div class="comment-button">
            <%= render 'book_comments/book_comments_button', book: @book, book_comment: @book_comment %>
          </div>


   </div>
  </div>
</div>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h2><%= @user.name %>さんとのチャット</h2>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.name %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.name %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>

            <%= form_with model: @chat, remote: true do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
            <% end %>
        </div>
    </div>
</div>